name: Test de construction Docker

on:
  push:
    branches: [ "main", "master" ] 
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test-build:
    name: Vérifier le build Docker
    runs-on: ubuntu-latest 

    steps:
     
      - name: Récupérer le code source
        uses: actions/checkout@v4

      - name: Tester la construction de l'image web
        run: docker compose build
