name: CI - Pipeline complet Docker & PHP

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  validation-projet:
    name: Vérification globale du projet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code source
        uses: actions/checkout@v7

      - name:  Configuration de l'environnement PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name:  Analyse de la syntaxe du code PHP
        run: php -l src/index.php

      - name:  Configuration de Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name:  Construction de l'environnement Docker
        run: docker compose build

      - name:  Démarrage des conteneurs en arrière-plan
        run: docker compose up -d

      - name:  Vérification de l'état du serveur
        run: |
          sleep 5
          docker compose ps
          curl -f -I http://localhost:8086 || exit 1
